### ISSUE TITLE
Solidus codebase has many dynamic finders

### ISSUE THREAD

**Issue by spaghetticode** [solidusio/solidus#1881]
I am having issues integrating the `solidus_globalize` gem, issues that are related to the presence in solidus codebase of many dynamic finders such as `find_by_permalink!`, `find_by_name!` and so on, which as far as I know are/will be deprecated in rails.

I am only a beginner with solidus and its ecosystem, but I think that those finders should be replaced with on of these types of code:
```
where(field: "value").first!
find_by!(field: "value")
```
with the multiple benefits of: 
* fixing the issues with the `solidus_globalize` gems
* preparing `solidus` codebase for the moment when those dynamic finders will be completely removed

I think that myself (or somebody else at my company) may be able to handle this task and provide a PR in the next few days if there is general consensus that the issue is real, that this is something that should be done and that the proposed solution is good and sound.

**Comment by tvdeyen** [comment]
👍 

First step taken by https://github.com/solidusio/solidus/pull/1880

**Comment by AndreiMotinga** [comment]
I'd like to take a stab at it. Since I'm just starting out with open source,  any advice or guidance on how I should approach this would be appreciated.

**Comment by jhawthorn** [comment]
> I am having issues integrating the solidus_globalize gem, issues that are related to the presence in solidus codebase of many dynamic finders such as find_by_permalink!, find_by_name! and so on, which as far as I know are/will be deprecated in rails.

These are *not* deprecated and there's no indication that they ever will be (quite the opposite). It is a misconception because some other dynamic finders were removed from rails (ages ago in rails 4.0).

From [activerecord-deprecated_finders README](https://github.com/rails/activerecord-deprecated_finders/blob/master/README.md):

> Note that find(primary_key), find_by..., and find_by...! are not deprecated.

So it is a globalize bug (globalize/globalize#423) and it should be fixed there. I'm not totally comfortable with us making changes simply because another library is broken.

**Comment by AndreiMotinga** [comment]
> I'm not totally comfortable with us making sweeping changes simply because another library is broken.

I agree, it makes sense. However, in this particular case, the change required is very simple and won't change anything about the solidus, other than make it slightly more flexible.  

Plus, even when some other translation project will appear, will it face the same problem ?

**Comment by spaghetticode** [comment]
@jhawthorn thanks for the insight. 

As you correctly wrote those dynamic finders are not actually deprecated *right now*, but according to https://github.com/rails/rails/blob/master/activerecord/lib/active_record/base.rb their usage is already sort of discouraged:

```
  # == Dynamic attribute-based finders
  #
  # Dynamic attribute-based finders are a mildly deprecated way of getting (and/or creating) objects
  # by simple queries without turning to SQL. They work by appending the name of an attribute
  # to <tt>find_by_</tt> like <tt>Person.find_by_user_name</tt>.
  # Instead of writing <tt>Person.find_by(user_name: user_name)</tt>, you can use
  # <tt>Person.find_by_user_name(user_name)</tt>.
```
I still see replacing __mildly deprecated__ code an improvement, however small it might be, with the immediate bonus that the *only available* internationalization gem for solidus will start to work well again.

**Comment by mamhoff** [comment]
Closed via #1886
